name: es_drawer_controller_example
description: Sample project to show how to use es_drawer_controller

publish_to: 'none'

version: 1.0.3+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  share: ^2.0.1
  url_launcher: ^6.0.3
  flutter:
    sdk: flutter

  es_drawer_controller:
    path: ../


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ic_launcher.png